### ISSUE TITLE
"Object reference not set to an instance of an object" in various views

### ISSUE THREAD

**Issue by bond4u** [ShokoAnime/ShokoDesktop#185]
Upgraded to 3.4.3.2 and got this message.
Utilities > Multiple Files > refresh > this error message for lots of entries
Restarted database - "drop database jmm" in mysql, and full import, but I still get this message.
Now I also get it in Utilities > Manually linked > type "stei" > steins;gate shows up > expand one > entry is shown and this error appears > press ok > window stops updating > can only close window > window disappears, but process is still running.

**Comment by bond4u** [comment]
Can't drop whole jmmdesktop.log here for some reason, so I'll just paste last page from log:

[2015-08-12 10:04:22:768] Error|ExceptionFilterHelper.TryCatchWhen => Dispatcher.CatchException => App.Current_DispatcherUnhandledException System.InvalidOperationException: Dispatcher processing has been suspended, but messages are still being processed.
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
[2015-08-12 10:04:24:766] Error|ExceptionFilterHelper.TryCatchWhen => Dispatcher.CatchException => App.Current_DispatcherUnhandledException System.InvalidOperationException: Dispatcher processing has been suspended, but messages are still being processed.
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
[2015-08-12 10:04:26:763] Error|ExceptionFilterHelper.TryCatchWhen => Dispatcher.CatchException => App.Current_DispatcherUnhandledException System.InvalidOperationException: Dispatcher processing has been suspended, but messages are still being processed.
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
[2015-08-12 10:04:28:758] Error|ExceptionFilterHelper.TryCatchWhen => Dispatcher.CatchException => App.Current_DispatcherUnhandledException System.InvalidOperationException: Dispatcher processing has been suspended, but messages are still being processed.
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
[2015-08-12 10:04:30:034] Error|AniDB_AnimeVM.get_Detail => AniDB_AnimeDetailedVM.Populate => Utils.ShowErrorMessage System.NullReferenceException: Object reference not set to an instance of an object.
   at JMMClient.ViewModel.AniDB_AnimeDetailedVM.Populate(Contract_AniDB_AnimeDetailed contract, Int32 animeID) in c:\Projects\GitHub\jmmclient\JMMClient\ViewModel\AniDB_AnimeDetailedVM.cs:line 163
[2015-08-12 10:06:48:561] Trace|BackgroundWorker.WorkerThreadStart => MainWindow.showDashboardWorker_DoWork => DashboardVM.RefreshData Dashboard Time: RefreshGroupsSeriesData: 1729,0989
[2015-08-12 10:06:51:857] Warn|UTorrentHelperVM.Init => UTorrentHelper.Init => UTorrentHelper.PopulateToken Credentials are not valid for uTorrent
[2015-08-12 10:07:07:460] Error|ExceptionFilterHelper.TryCatchWhen => Dispatcher.CatchException => App.Current_DispatcherUnhandledException System.InvalidOperationException: Dispatcher processing has been suspended, but messages are still being processed.
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
[2015-08-12 10:07:08:997] Error|AniDB_AnimeVM.get_Detail => AniDB_AnimeDetailedVM.Populate => Utils.ShowErrorMessage System.NullReferenceException: Object reference not set to an instance of an object.
   at JMMClient.ViewModel.AniDB_AnimeDetailedVM.Populate(Contract_AniDB_AnimeDetailed contract, Int32 animeID) in c:\Projects\GitHub\jmmclient\JMMClient\ViewModel\AniDB_AnimeDetailedVM.cs:line 163

**Comment by jmediamanager** [comment]
Hi is there anywhere you can upload the whole (including jmm server log)

Would be best if you remove logs, reproduce the error and then send them

Thanks

**Comment by bond4u** [comment]
https://dl.dropboxusercontent.com/u/9687879/jmmserver-2015-08-12.log
https://dl.dropboxusercontent.com/u/9687879/jmmdesktop-2015-08-12.log

**Comment by ElementalCrisis** [comment]
Issue is five years old and doesn't seem to be a problem anymore.
