### ISSUE TITLE
JsonSerializationException when viewing collection 

### ISSUE THREAD

**Issue by KingJ** [ShokoAnime/ShokoDesktop#543]
## Version Information

Server: japanesemediamanager/ShokoServer@39d759cb61593f89ac0a26b8a0d4f55c2c5976e7
Desktop: japanesemediamanager/ShokoDesktop@cbf8431cc618a41c3a33a08b38baa3c2a1caeef9

Although these are not the most recent daily builds, I am currently using these due to an unrelated Linux build issue.

## LOG FILE
```
[2017-07-15 21:27:17:339] Info|CommandBinding.OnExecuted => MainWindow.RefreshView => VM_AnimeSeries_User.RefreshEpisodes Got episode data from service: Accel World in 60.9651 ms
[2017-07-15 21:27:17:339] Info|CommandBinding.OnExecuted => MainWindow.RefreshView => VM_AnimeSeries_User.RefreshEpisodes Got episode contracts: Accel World in 0.5016 ms
[2017-07-15 21:27:17:353] Info|CommandBinding.OnExecuted => MainWindow.RefreshView => VM_AnimeSeries_User.RefreshEpisodes Sorted episode contracts: Accel World in 0.5015 ms
[2017-07-15 21:27:21:056] Error|VM_AnimeEpisode_User.get_FilesForEpisode => VM_AnimeEpisode_User.RefreshFilesForEpisode => Utils.ShowErrorMessage System.AggregateException: One or more errors occurred. ---> Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.List`1[Shoko.Models.Client.CL_VideoDetailed]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'AnimeEpisodeID', line 1, position 18.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Nancy.Rest.Client.Rest.SmallWebClient.<RestRequest>d__0.MoveNext() in C:\Users\mpiva\Documents\GIT\Nancy.Rest\Nancy.Rest.Client\Rest\SmallWebClient.cs:line 70
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nancy.Rest.Client.ClientFactory.<>c__DisplayClass2_0.<<DoSyncClient>b__0>d.MoveNext() in C:\Users\mpiva\Documents\GIT\Nancy.Rest\Nancy.Rest.Client\ClientFactory.cs:line 176
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Nancy.Rest.Client.ClientFactory.DoSyncClient(Object dexp, MethodDefinition def, IWebProxy proxy, Object[] parameters) in C:\Users\mpiva\Documents\GIT\Nancy.Rest\Nancy.Rest.Client\ClientFactory.cs:line 176
   at Nancy.Rest.Client.ClientFactory.<>c__DisplayClass1_1`1.<Create>b__14(Object a, Object b) in C:\Users\mpiva\Documents\GIT\Nancy.Rest\Nancy.Rest.Client\ClientFactory.cs:line 128
   at CallSite.Target(Closure , CallSite , Object , Int32 , Int32 )
   at ActLike_IShokoServer_0e11557dd2bc486bba0f9e309ebb7d56.GetFilesForEpisode(Int32 episodeID, Int32 userID)
   at Shoko.Desktop.ViewModel.Server.VM_AnimeEpisode_User.RefreshFilesForEpisode() in C:\projects\jmmclient\Shoko.Desktop\ViewModel\Server\VM_AnimeEpisode_User.cs:line 1041
---> (Inner Exception #0) Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.List`1[Shoko.Models.Client.CL_VideoDetailed]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'AnimeEpisodeID', line 1, position 18.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Nancy.Rest.Client.Rest.SmallWebClient.<RestRequest>d__0.MoveNext() in C:\Users\mpiva\Documents\GIT\Nancy.Rest\Nancy.Rest.Client\Rest\SmallWebClient.cs:line 70
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nancy.Rest.Client.ClientFactory.<>c__DisplayClass2_0.<<DoSyncClient>b__0>d.MoveNext() in C:\Users\mpiva\Documents\GIT\Nancy.Rest\Nancy.Rest.Client\ClientFactory.cs:line 176<---
```

## Description

When viewing a series's information on the collection screen, an error box appears when first viewing the information. The error log points towards a JsonSerializationException.

## STEPS TO REPRODUCE

1) Click Collection.
2) Enter the 'All' Group. The list of series appears on the left hand pane, but the right information pane remains blank.
3) A error box appears with the text "One or more errors occurred.". The log message above is generated in the log file at the same time.
4) Click OK on the error box, the series information appears in the right hand pane.
5) Click any other series in the left hand pane, steps 3 and 4 recur.

**Comment by KingJ** [comment]
I've upgraded to the latest dailies (server: ShokoAnime/ShokoServer@564e68137a0e633ceb8762ede278f63044f413f9 desktop: 5ac1f0107ec22c94000cd2e6713f41b12ae38f13) and I am no longer receiving this error.
