### ISSUE TITLE
AVDump giving an error trying to open clipboard

### ISSUE THREAD

**Issue by de-odex** [ShokoAnime/ShokoDesktop#544]
## VERSION INFORMATION

Server Version: 3.8.0.0

Desktop Version: 3.8.0.0

## LOG FILE

```
[2017-07-27 00:29:10:067] Error|FrameworkElement.RaiseDependencyPropertyChanged => AvdumpFileControl.AvdumpFileControl_DataContextChanged => Utils.ShowErrorMessage System.Runtime.InteropServices.COMException (0x800401D0): OpenClipboard Failed (Exception from HRESULT: 0x800401D0 (CLIPBRD_E_CANT_OPEN))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Windows.Clipboard.CriticalSetDataObject(Object data, Boolean copy)
   at System.Windows.Clipboard.SetDataObject(Object data)
   at Shoko.Desktop.UserControls.AvdumpFileControl.SetED2KDump(String result) in D:\My Files\Documents\GitHub\ShokoClient\Shoko.Desktop\UserControls\AvdumpFileControl.xaml.cs:line 245
   at Shoko.Desktop.UserControls.AvdumpFileControl.AvdumpFileControl_DataContextChanged(Object sender, DependencyPropertyChangedEventArgs e) in D:\My Files\Documents\GitHub\ShokoClient\Shoko.Desktop\UserControls\AvdumpFileControl.xaml.cs:line 192
```

## DESCRIPTION

Clicking on AVDump queued files spits out this error
![shokodesktop_2017-july-25_16 19 54](https://user-images.githubusercontent.com/11498305/28632460-35339aac-7263-11e7-8145-cc5c8b735675.png)

## STEPS TO REPRODUCE

Queue more than 2 files (not equal, it doesn't always happen) for AVDump, click on them sequentially

**Comment by da3dsoul** [comment]
Google this error. It's a weird one.
`COMException (0x800401D0): OpenClipboard Failed (Exception from HRESULT: 0x800401D0 (CLIPBRD_E_CANT_OPEN))`

**Comment by da3dsoul** [comment]
I made a "fix" based on info I've seen on various threads. If another program is continuously locking the clipboard (firefox and skype have been known to do this when they break), then it won't help.
