### ISSUE TITLE
Version 3.8 Beta Issues

### ISSUE THREAD

**Issue by ElementalCrisis** [ShokoAnime/ShokoDesktop#546]
## VERSION INFORMATION

Server Version: 3.8.0.0
Desktop Version: 3.8.0.0

## LOG FILE

No log

## DESCRIPTION

![image](https://user-images.githubusercontent.com/9443295/28766295-db828a76-7583-11e7-9e61-a1b58edf1cdd.png)

Dashboard - Simple View 

Play Next Episode button does not work.
Characters section do not load.
You May Also Like section does not load.

Collection - Normal View

Tags do not load.

![image](https://user-images.githubusercontent.com/9443295/28766361-1eb354f6-7584-11e7-99c0-63704e06ac12.png)

Related / Similar not being pulled correctly. Series 11 Eyes lists no similar anime on AniDB yet two shows are listed. http://anidb.net/perl-bin/animedb.pl?show=anime&aid=6751

AniDB comments are longer loaded.

![image](https://user-images.githubusercontent.com/9443295/28766335-07a79a74-7584-11e7-8ab9-b35e48ca09bb.png)

Group Info is not being populated even though files were hashed and have a match on AniDB.

**Comment by da3dsoul** [comment]
Mk time to start listing what I've already fixed before you made this. Tags, related and similar, and NO GROUP INFO were all already fixed. I may have already fixed comments, but I'll need to look to see

**Comment by da3dsoul** [comment]
I don't use simple view, so I'm not surprised half of it is broken

**Comment by ElementalCrisis** [comment]
Oh cool, I take it you haven't pushed your fixed yet?

**Comment by da3dsoul** [comment]
You did. It was a general clean up to AniDB scraping

**Comment by ElementalCrisis** [comment]
Ah ok cool, I'll update the beta later tonight.

**Comment by ElementalCrisis** [comment]
On a fresh install of Shoko Server with a fresh DB.

```
[2017-07-30 22:04:37:519] Error|ShokoServer.WorkerSetupDB_DoWork => ShokoServer.NetPermissionWrapper => ShokoServer.StartNancyHost Nancy.Hosting.Self.AutomaticUrlReservationCreationFailureException: The Nancy self host was unable to start, as no namespace reservation existed for the provided url(s).

Please either enable UrlReservations.CreateAutomatically on the HostConfiguration provided to 
the NancyHost, or create the reservations manually with the (elevated) command(s):

netsh http add urlacl url="http://+:8111/" user="Everyone"

   at Nancy.Hosting.Self.NancyHost.StartListener()
   at Nancy.Hosting.Self.NancyHost.Start()
   at Shoko.Server.ShokoServer.StartNancyHost() in D:\My Files\Documents\GitHub\ShokoServer\Shoko.Server\ShokoServer.cs:line 1651
```

Previously, when the user started Shoko, if a config file was not found the user was given the option to select one. Then Shoko would restart as Admin, do what it needs to do and then restart as a regular user. This no longer happens and causes the above errors and errors writing to the SQLite DB. 

```
[2017-07-30 22:17:16:047] Error|App.OnStartup => ServerSettings.LoadSettingsFromFile => ServerSettings.LoadLegacySettingsFromFile Error occured during LoadSettingsManuallyFromFile: The string parameter 'fileMap.ExeConfigFilename' cannot be null or empty.
Parameter name: fileMap.ExeConfigFilename
[2017-07-30 22:17:16:313] Info|Application.<.ctor>b__1_0 => App.OnStartup => ServerSettings.LoadSettingsFromFile User has fresh config, restarting once as admin.
[2017-07-30 22:17:16:328] Info|App.OnStartup => ServerSettings.LoadSettingsFromFile => Utils.RestartAsAdmin RestartAsAdmin batch line: timeout 5 && taskkill /F /IM ShokoServer.exe /fi "memusage gt 2" && "D:\Program Files (x86)\Shoko\Shoko Server\ShokoServer.exe"
[2017-07-30 22:19:19:651] Warn|MainWindow..ctor => ShokoServer.StartUpServer => ServerSettings.DebugSettingsToLog Error in log (database version lookup: Object reference not set to an instance of an object.
```

This was the message box you'd seen on a fresh install of Server.
![image](https://user-images.githubusercontent.com/9443295/28812245-abf5ffde-7648-11e7-83ec-530dd9bf0828.png)

Logs Related to it. 
Server - [2017-07-30_-_Server.txt](https://github.com/ShokoAnime/ShokoDesktop/files/1189677/2017-07-30_-_Server.txt)

- There's also an issue with the AniDB poster not downloading correctly causing Shoko Desktop to crash, here's the log for it. Deleting the image and running the Update Images button fixed it.

Desktop
[2017-07-30.zip](https://github.com/ShokoAnime/ShokoDesktop/files/1189678/2017-07-30.zip)

**Comment by Jimmyson** [comment]
For the settings migration, is there a way to dynamically set the Registry Path for the installation?
"HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\{898530ED-CFC7-4744-B2B8-A8D98A2FA06C}_is1" is the path stated, but mine has a different GUID value.
{0BA2D22B-A0B7-48F8-8AA1-BAAEFC2034CB}_is1

**Comment by ElementalCrisis** [comment]
@da3dsoul on latest commit, Realted & Similar still show nothing and Group Info is still set to UNKNOWN.

**Comment by ElementalCrisis** [comment]
Also my Server log is filled with these.

```[2017-08-13 15:57:25:529] Error|BackgroundWorker.OnDoWork => CommandProcessorGeneral.WorkerCommands_DoWork => CommandRequest_GetAnimeHTTP.ProcessCommand Error processing CommandRequest_GetAnimeHTTP: 13060 - NHibernate.Exceptions.GenericADOException: could not insert: [Shoko.Models.Server.AniDB_Anime_Character][SQL: INSERT INTO AniDB_Anime_Character (AnimeID, CharID, CharType, EpisodeListRaw) VALUES (?, ?, ?, ?); select last_insert_rowid()] ---> System.Data.SQLite.SQLiteException: constraint failed
NOT NULL constraint failed: AniDB_Anime_Character.EpisodeListRaw
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at NHibernate.AdoNet.AbstractBatcher.ExecuteReader(IDbCommand cmd)
   at NHibernate.Id.IdentityGenerator.InsertSelectDelegate.ExecuteAndExtract(IDbCommand insert, ISessionImplementor session)
   at NHibernate.Id.Insert.AbstractReturningDelegate.PerformInsert(SqlCommandInfo insertSQL, ISessionImplementor session, IBinder binder)
   --- End of inner exception stack trace ---
   at NHibernate.Id.Insert.AbstractReturningDelegate.PerformInsert(SqlCommandInfo insertSQL, ISessionImplementor session, IBinder binder)
   at NHibernate.Persister.Entity.AbstractEntityPersister.Insert(Object[] fields, Object obj, ISessionImplementor session)
   at NHibernate.Action.EntityIdentityInsertAction.Execute()
   at NHibernate.Engine.ActionQueue.Execute(IExecutable executable)
   at NHibernate.Event.Default.AbstractSaveEventListener.PerformSaveOrReplicate(Object entity, EntityKey key, IEntityPersister persister, Boolean useIdentityColumn, Object anything, IEventSource source, Boolean requiresImmediateIdAccess)
   at NHibernate.Event.Default.AbstractSaveEventListener.SaveWithGeneratedId(Object entity, String entityName, Object anything, IEventSource source, Boolean requiresImmediateIdAccess)
   at NHibernate.Event.Default.DefaultSaveOrUpdateEventListener.SaveWithGeneratedOrRequestedId(SaveOrUpdateEvent event)
   at NHibernate.Event.Default.DefaultSaveOrUpdateEventListener.EntityIsTransient(SaveOrUpdateEvent event)
   at NHibernate.Event.Default.DefaultSaveOrUpdateEventListener.OnSaveOrUpdate(SaveOrUpdateEvent event)
   at NHibernate.Impl.SessionImpl.FireSaveOrUpdate(SaveOrUpdateEvent event)
   at NHibernate.Impl.SessionImpl.SaveOrUpdate(Object obj)
   at Shoko.Server.Repositories.BaseDirectRepository`2.Save(IReadOnlyCollection`1 objs) in D:\Documents\GitHub\ShokoServer\Shoko.Server\Repositories\BaseDirectRepository.cs:line 156
   at Shoko.Server.Models.SVR_AniDB_Anime.CreateCharacters(ISession session, List`1 chars) in D:\Documents\GitHub\ShokoServer\Shoko.Server\Models\SVR_AniDB_Anime.cs:line 1230
   at Shoko.Server.Models.SVR_AniDB_Anime.PopulateAndSaveFromHTTP(ISession session, Raw_AniDB_Anime animeInfo, List`1 eps, List`1 titles, List`1 cats, List`1 tags, List`1 chars, List`1 rels, List`1 sims, List`1 recs, Boolean downloadRelations) in D:\Documents\GitHub\ShokoServer\Shoko.Server\Models\SVR_AniDB_Anime.cs:line 1064
   at Shoko.Server.AniDBHelper.SaveResultsForAnimeXML(ISession session, Int32 animeID, Boolean downloadRelations, AniDBHTTPCommand_GetFullAnime getAnimeCmd) in D:\Documents\GitHub\ShokoServer\Shoko.Server\AniDBHelper.cs:line 1080
   at Shoko.Server.AniDBHelper.GetAnimeInfoHTTP(ISession session, Int32 animeID, Boolean forceRefresh, Boolean downloadRelations) in D:\Documents\GitHub\ShokoServer\Shoko.Server\AniDBHelper.cs:line 1067
   at Shoko.Server.AniDBHelper.GetAnimeInfoHTTP(Int32 animeID, Boolean forceRefresh, Boolean downloadRelations) in D:\Documents\GitHub\ShokoServer\Shoko.Server\AniDBHelper.cs:line 1017
   at Shoko.Server.Commands.CommandRequest_GetAnimeHTTP.ProcessCommand() in D:\Documents\GitHub\ShokoServer\Shoko.Server\Commands\AniDB\CommandRequest_GetAnimeHTTP.cs:line 54```

**Comment by ElementalCrisis** [comment]
Also every series I add fails to properly download the AniDB poster crashing Desktop.

**Comment by da3dsoul** [comment]
Hmm ok. Any log for the failed poster downloads

**Comment by ElementalCrisis** [comment]
For TvDB Images

```
[2017-08-13 16:04:45:086] Warn|BackgroundWorker.OnDoWork => CommandProcessorImages.WorkerCommands_DoWork => CommandRequest_DownloadImage.ProcessCommand Error processing CommandRequest_DownloadImage: http://thetvdb.com/banners/fanart/original/87991-2.jpg (23) - The image download stream returned an invalid image
[2017-08-13 16:04:45:121] Info|BackgroundWorker.OnDoWork => CommandProcessorImages.WorkerCommands_DoWork => CommandRequest_DownloadImage.ProcessCommand Processing CommandRequest_DownloadImage: 24
[2017-08-13 16:04:50:570] Warn|BackgroundWorker.OnDoWork => CommandProcessorImages.WorkerCommands_DoWork => CommandRequest_DownloadImage.ProcessCommand Error processing CommandRequest_DownloadImage: http://thetvdb.com/banners/fanart/original/87991-3.jpg (24) - The image download stream returned an invalid image
[2017-08-13 16:05:00:108] Info|BackgroundWorker.OnDoWork => CommandProcessorImages.WorkerCommands_DoWork => CommandRequest_DownloadImage.ProcessCommand Processing CommandRequest_DownloadImage: 23
```
Here's my log with some other errors I've noticed.

[2017-08-13.txt](https://github.com/ShokoAnime/ShokoDesktop/files/1220999/2017-08-13.txt)

Seems the issue is, the image is never downloaded so when Desktop goes to load the imagefile, it creates a 0KB one since it can't find it and crashes.

I added Cowboy Bebop, the AniDB Image filename is 156726.jpg yet there is no record in my log for it.

**Comment by da3dsoul** [comment]
It shouldn't save if it's invalid

**Comment by da3dsoul** [comment]
We may need to deprecate image downloading from TvDB, as TvDBSharper handles that

**Comment by ElementalCrisis** [comment]
Yeah that would solve the TvDB downloading issue, now to figure out why posters aren't being downloaded from AniDB or anything logged about it.

**Comment by da3dsoul** [comment]
I'm not having any issues with covers downloading.

**Comment by da3dsoul** [comment]
From discord:
> finally I can reproduce it... - in metro Dashboard the "refresh circle" will get permanent (wont disappear) when you go and pin a serie before hitting the refresh button
> so steps are - dashboard view --> click a serie --> use the pin button --> go back to dashboard --> hit the back button --> hit refresh for the list

**Comment by ElementalCrisis** [comment]
[] Adding a new series via Utilities - Unrecognized - New Series produces an error 

```
[2017-08-26 17:56:44:082] Error|EventRoute.InvokeHandlersImpl => NewSeries.btnConfirm_Click => Utils.ShowErrorMessage System.AggregateException: One or more errors occurred. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Nancy.Rest.Client.ClientFactory.DoSyncClient(Object dexp, MethodDefinition def, IWebProxy proxy, Object[] parameters)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute7[T0,T1,T2,T3,T4,T5,T6,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6)
   at Nancy.Rest.Client.ClientFactory.<>c__DisplayClass1_1`1.<Create>b__15(Object a, Object b, Object c)
   at CallSite.Target(Closure , CallSite , Object , Int32 , Nullable`1 , Int32 )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   at CallSite.Target(Closure , CallSite , Object , Int32 , Nullable`1 , Int32 )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   at ActLike_IShokoServer_fd039e6db49d4a4cbad74b49b700420d.CreateSeriesFromAnime(Int32 animeID, Nullable`1 animeGroupID, Int32 userID)
   at Shoko.Desktop.Forms.NewSeries.btnConfirm_Click(Object sender, RoutedEventArgs e) in D:\Documents\GitHub\ShokoDesktop\Shoko.Desktop\Forms\NewSeries.xaml.cs:line 289
---> (Inner Exception #0) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

[2017-08-26 17:56:45:374] Error|EventRoute.InvokeHandlersImpl => UnrecognisedVideos.btnAddSeries_Click => Utils.ShowErrorMessage System.NullReferenceException: Object reference not set to an instance of an object.
   at Shoko.Desktop.UserControls.UnrecognisedVideos.btnAddSeries_Click(Object sender, RoutedEventArgs e) in D:\Documents\GitHub\ShokoDesktop\Shoko.Desktop\UserControls\UnrecognisedVideos.xaml.cs:line 342
```

**Comment by da3dsoul** [comment]
Is there an error in server? That sounds like a server error

**Comment by ElementalCrisis** [comment]
Nothing in the logs from what I could see. I'll try again after the new DB is done.

**Comment by ElementalCrisis** [comment]
![image](https://user-images.githubusercontent.com/9443295/29749497-41b0814a-8ae2-11e7-974f-05e3ee4a78d2.png)
- [ ] Fansub group info is not populated. 

![image](https://user-images.githubusercontent.com/9443295/29749508-86aac724-8ae2-11e7-8a4a-9238dccaeaaa.png)

- [ ] Series images are being duplicated. 
- [ ] Validate images does not replace invalid images.

**Comment by Cazzar** [comment]
Just looked into the fansub group info.
it is downloaded.
https://github.com/ShokoAnime/ShokoServer/blob/aa5f05782cf2da140a7189e879c80b23e2e1a21b/Shoko.Server/AniDBHelper.cs#L410-L415
You just need 
`"AniDB_DownloadReleaseGroups": "True"` in your config.

**Comment by ElementalCrisis** [comment]
@Cazzar Had to disable and re-enable to get it to work, but that did the trick.

**Comment by da3dsoul** [comment]
That's why I couldn't reproduce it. I've had that on

**Comment by LovShoko** [comment]
ShokoDestkop stopped showing the "renamed" file name instead it displays the original filename
@Cazzar was in favour of displaying the filename as it currently is and not something it WAS
(a user on discord "Jio" didnt think its a big deal and after @Cazzar stated he is in favor of it - "Jio" suggested some options to configure it)
![image](https://user-images.githubusercontent.com/31392944/29754183-7275f44c-8b80-11e7-9e37-09262bd425d9.png)

why does shoko say 3 episodes on this serie
![image](https://cdn.discordapp.com/attachments/96235819366371328/351377504784744448/image.png)


The following already got solved by me - I simply deleted the serie and re-imported the files in question
Have a look at the screenshot
![image](https://cdn.discordapp.com/attachments/96235819366371328/351377973758263297/image.png)

In it you can see multipe errors:
1. the "1-OVA" (2nd entry) is actually from a different serie
2. the same image for "different" episodes (as I said it is actually of a different serie)
3. the file is stored (drop destination) with the correct serie (see tooltip of the file)

**Comment by ElementalCrisis** [comment]
I'd check your log for any importing issues, everything loaded correctly for me. 

![image](https://user-images.githubusercontent.com/9443295/29754421-4657cc60-8b39-11e7-85cb-4f70515db8b9.png)

**Comment by LovShoko** [comment]
@ElementalCrisis - as I said re-importing solved the issue for me it aswell
dont know what was wrong in the first place

just checked the episode counter again on my side - since yours displays 2 episodes now mine also displays the count correctly - maybe some caching issue

gona edit my question and remove the part about the counter being wrong

**Comment by ElementalCrisis** [comment]
Duplicate images has been fixed. 

Validating Images only works **IF** Shoko Desktop is closed.

**Comment by da3dsoul** [comment]
Fixed group exclusion settings

**Comment by Cazzar** [comment]
Checked off anidb comments not loading per: 
![image](https://user-images.githubusercontent.com/994214/30003342-ef15fa82-90fe-11e7-8a12-49a828c241cc.png)

**Comment by Cazzar** [comment]
As with the adding new group, that is working.

**Comment by da3dsoul** [comment]
So the only thing left in this issue at this point is:
From discord:

> finally I can reproduce it... - in metro Dashboard the "refresh circle" will get permanent (wont disappear) when you go and pin a serie before hitting the refresh button
so steps are - dashboard view --> click a serie --> use the pin button --> go back to dashboard --> hit the back button --> hit refresh for the list

**Comment by LovShoko** [comment]
@da3dsoul 
Thats not correct.

There are still those points open:

- ShokoDestkop stopped showing the "renamed" file name instead it displays the original filename
  @Cazzar was in favour of displaying the filename as it currently is and not something it WAS
  (a user on discord "Jio" didnt think its a big deal and after @Cazzar stated he is in favor of it - "Jio" suggested some options to configure it)
  https://user-images.githubusercontent.com/31392944/29754183-7275f44c-8b80-11e7-9e37-09262bd425d9.png
 
- the "Mark ALL Watched/Unwatched" buttons dont update the episodes (still display watched/unwatched symbols) - and nothing acutally updates the counter of unwatched episodes (have to manully refresh)
 
- Shoko seems to respect indirectly related series when grouping - can I vote to have it in the exlude list

(The first 2 are bugs, and the second is a request from me)

**Comment by da3dsoul** [comment]
1. @Cazzar said he couldn't reproduce it
2. True I forgot that
3. No. It leads to unpredictable results depending on the order that series are grouped

**Comment by LovShoko** [comment]
1. To again verify the problem, I went ahead and downloaded the following file:
[(́◉◞౪◟◉‵)] Mobile Suit Gundam Twilight AXIS - 05 ／ 機動戦士ガンダム Twilight AXIS 第5話 [720p].mkv
(FYI - though I believe it doesnt matter - I dont have any Gundam Serie in my Collection)

And after importing I get this:
![image](https://user-images.githubusercontent.com/31392944/30235700-d209e14a-950b-11e7-8eaa-40df2067a6ad.png)

Notice the tooltip, thats the correct and current filename.
So.... totally reproducable on my end.

2. Bad boy.
3. Okay, no problem since I solved the issue at hand with the mentioned settings.

----

I had another look at my discord history and found the following stuff that I forgot (bad boy me) to post here and I verified that they are aswell still open:

- I am no fan of Shoko settinging up "everyone" to have full access in its folder
https://cdn.discordapp.com/attachments/96235819366371328/350810425102827531/image.png
Still the case, even though @ElementalCrisis said its a temporary fix and @maxpiva did something that this shouldnt be necessary, he pointed to this page https://github.com/ShokoAnime/ShokoServer/commit/ec7796933d997a52fc626eafa30672e8725c39e7 and claimed that was the fix to resolve the need of "everyone" needing full access

- Play next episde button gives the following message, when the file shortly open by mpc, happens easily when you watch a playlist and close mpc the second the next file starts, and want to continue the next day:
![image](https://user-images.githubusercontent.com/31392944/30235794-6faf891c-950d-11e7-902e-0e59161cd270.png)

- https://cdn.discordapp.com/attachments/96235819366371328/350979755727912960/image.png
StackTrace: https://pastebin.com/AKJ0wWMJ

- not sure whats going on here
https://cdn.discordapp.com/attachments/96235819366371328/351492096936509442/image.png
the folder icon gives the following error for the first entry
https://cdn.discordapp.com/attachments/96235819366371328/351492268731138048/image.png

just checked my local storage and I see this
https://cdn.discordapp.com/attachments/96235819366371328/351492537749471242/image.png
is the ":" problematic?
seems like in an older version ":" was okay, but in newest version ":" is bad

(both directories got created by drop destination stuff)

@da3dsoul asked me:
The ":" is part of the Unicode character thing. There is a lot that could be going on there. Are there files in the one without the colon? Did Shoko import them? Are drop folders set up? What is the source and destination? Were all of the files placed with drop folders, or only some of them? Our import system is extremely customizable, so there are many ways to get different results than expected. 3.8 handles importing much better, so you can actually move all of those files to a drop source and they'll be reorganized without a long annoying Queue

I answered:
yes, there are files in both folders - yes, shoko did import them - yes, there is 1 drop folder set up (the folder both Naruto: The Last Movie folders got created) - dont get what you want to know with "What is the source and destination?" - yes, both files where in drop folder - but as I mentioned not at the same time (have a look at the date the folders got created) - just forgot I had it already in shoko and tried to import again and now shoko does it with ":", but I dont really mind the 2 different folders  what I am more worried about is that shokodesktop doesnt display the file (in ":" folder) and doesnt let me delete it

**Comment by da3dsoul** [comment]
The characters thing is still not fixed, but a separate issue can be made
