### ISSUE TITLE
Error when rescanning all unknown items

### ISSUE THREAD

**Issue by Baine** [ShokoAnime/ShokoDesktop#558]
## VERSION INFORMATION

Server Version: 
docker cazzar/shokoserver:daily

Desktop Version: 
849049b5b7d67cfd7128c116750bdbf650b7db6d

## LOG FILE

```
[2017-09-18 14:58:03:328] Error|EventRoute.InvokeHandlersImpl => UnrecognisedVideos.btnRescan_Click => Utils.ShowErrorMessage System.AggregateException: One or more errors occurred. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Nancy.Rest.Client.ClientFactory.DoSyncClient(Object dexp, MethodDefinition def, IWebProxy proxy, Object[] parameters)
   at Nancy.Rest.Client.ClientFactory.<>c__DisplayClass1_1`1.<Create>b__12()
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid1[T0](CallSite site, T0 arg0)
   at Shoko.Desktop.UserControls.UnrecognisedVideos.btnRescan_Click(Object sender, RoutedEventArgs e) in C:\Users\Paul\Documents\GitHub\ShokoDesktop\Shoko.Desktop\UserControls\UnrecognisedVideos.xaml.cs:line 290
---> (Inner Exception #0) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---
```
## DESCRIPTION

When clicking "Rescann All" in Utilities -> Unrecognized, ShokoDesktop shows (after locking up for a moment) a popup stating that an error occured, yet the files are queued for rescan.

## STEPS TO REPRODUCE

Have lots of unrecognized Files (in my case 7k+), hit rescan all in ShokoDesktop, Utilities, Unrecognized.

**Comment by da3dsoul** [comment]
Server log please. A task was cancelled means it's Server's daily

**Comment by Baine** [comment]
```
shokoserver    | 05:15:50| --- ProcessCommand exception: CommandRequest_RefreshAnime_687
shokoserver    | System.NullReferenceException: Object reference not set to an instance of an object
shokoserver    |   at Shoko.Server.Repositories.Cached.AniDB_VoteRepository+<>c.<GetByAnimeIDs>b__6_0 (Shoko.Models.Server.AniDB_Vote v) [0x00000] in <c07a32130d574416bbf1b71c41563ce3>:0
shokoserver    |   at System.Linq.Lookup`2[TKey,TElement].Create (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] keySelector, System.Collections.Generic.IEqualityComparer`1[T] comparer) [0x00017] in <e3fb361e66bb4797b6f56fd88e04971e>:0
shokoserver    |   at System.Linq.GroupedEnumerable`2[TSource,TKey].GetEnumerator () [0x00000] in <e3fb361e66bb4797b6f56fd88e04971e>:0
shokoserver    |   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] keySelector, System.Func`2[T,TResult] elementSelector, System.Collections.Generic.IEqualityComparer`1[T] comparer) [0x0007a] in <e3fb361e66bb4797b6f56fd88e04971e>:0
shokoserver    |   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] keySelector, System.Func`2[T,TResult] elementSelector) [0x00000] in <e3fb361e66bb4797b6f56fd88e04971e>:0
shokoserver    |   at Shoko.Server.Repositories.Cached.AniDB_VoteRepository.GetByAnimeIDs (System.Collections.Generic.IReadOnlyCollection`1[T] animeIDs) [0x00044] in <c07a32130d574416bbf1b71c41563ce3>:0
shokoserver    |   at Shoko.Server.Models.SVR_AnimeGroup.BatchGetVotes (System.Collections.Generic.IReadOnlyCollection`1[T] animeGroups) [0x00098] in <c07a32130d574416bbf1b71c41563ce3>:0
shokoserver    |   at Shoko.Server.Models.SVR_AnimeGroup.BatchUpdateContracts (Shoko.Server.Repositories.NHibernate.ISessionWrapper session, System.Collections.Generic.IReadOnlyCollection`1[T] animeGroups, System.Boolean updateStats) [0x00144] in <c07a32130d574416bbf1b71c41563ce3>:0
shokoserver    |   at Shoko.Server.Models.SVR_AnimeGroup.UpdateContract (Shoko.Server.Repositories.NHibernate.ISessionWrapper session, System.Boolean updatestats) [0x00000] in <c07a32130d574416bbf1b71c41563ce3>:0
shokoserver    |   at Shoko.Server.Repositories.Cached.AnimeGroupRepository.Save (Shoko.Server.Models.SVR_AnimeGroup grp, System.Boolean updategrpcontractstats, System.Boolean recursive, System.Boolean verifylockedFilters) [0x00052] in <c07a32130d574416bbf1b71c41563ce3>:0
shokoserver    |   at Shoko.Server.Models.SVR_AnimeGroup.UpdateStats (System.Boolean watchedStats, System.Boolean missingEpsStats) [0x00017] in <c07a32130d574416bbf1b71c41563ce3>:0
shokoserver    |   at Shoko.Server.Models.SVR_AnimeSeries.UpdateStats (System.Boolean watchedStats, System.Boolean missingEpsStats, System.Boolean updateAllGroupsAbove) [0x009ed] in <c07a32130d574416bbf1b71c41563ce3>:0
shokoserver    |   at Shoko.Server.Commands.CommandRequest_RefreshAnime.ProcessCommand () [0x00014] in <c07a32130d574416bbf1b71c41563ce3>:0
shokoserver    |   at Shoko.Server.Commands.CommandProcessorGeneral.WorkerCommands_DoWork (System.Object sender, System.ComponentModel.DoWorkEventArgs e) [0x00107] in <c07a32130d574416bbf1b71c41563ce3>:0
```

**Comment by da3dsoul** [comment]
Update, fixed already
