### ISSUE TITLE
Recommendations to Watch/Download

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/ShokoDesktop#561]
Non is shown, event after hiting "Get Missing Data Now" no data populate this tab on Dashboard 

Is this because bittorrent functionality was removed or intended ?

v3.8.0.1021

**Comment by bigretromike** [comment]
This could be related with fact that clicking "Get Missing Data Now" don't queue any commands.

**Comment by bigretromike** [comment]
Also when going thru Recommandation at Utility tab, and clicking "Get missing data" I get this error:

> [[2017-09-19 15:50:09:008] Error|BackgroundWorker.OnDoWork => MissingEpisodesControl.workerFiles_DoWork => Utils.ShowErrorMessage System.AggregateException: One or more errors occurred. ---> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
>    at System.String.CreateStringFromEncoding(Byte* bytes, Int32 byteLength, Encoding encoding)
>    at System.Text.UTF8Encoding.GetString(Byte[] bytes, Int32 index, Int32 count)
>    at System.Net.Http.HttpContent.ReadBufferedContentAsString()
>    at System.Net.Http.HttpContent.<WaitAndReturnAsync>d__63`2.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Nancy.Rest.Client.Rest.SmallWebClient.<RestRequest>d__0.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Nancy.Rest.Client.ClientFactory.<>c__DisplayClass2_0.<<DoSyncClient>b__0>d.MoveNext()
>    --- End of inner exception stack trace ---
>    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
>    at Nancy.Rest.Client.ClientFactory.DoSyncClient(Object dexp, MethodDefinition def, IWebProxy proxy, Object[] parameters)
>    at System.Dynamic.UpdateDelegates.UpdateAndExecute8[T0,T1,T2,T3,T4,T5,T6,T7,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7)
>    at Nancy.Rest.Client.ClientFactory.<>c__DisplayClass1_1`1.<Create>b__16(Object a, Object b, Object c, Object d)
>    at System.Dynamic.UpdateDelegates.UpdateAndExecute5[T0,T1,T2,T3,T4,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4)
>    at CallSite.Target(Closure , CallSite , Object , Int32 , Boolean , Boolean , Int32 )
>    at System.Dynamic.UpdateDelegates.UpdateAndExecute5[T0,T1,T2,T3,T4,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4)
>    at ActLike_IShokoServer_c4908871d66c456ebee5c50abf20aece.GetMissingEpisodes(Int32 userID, Boolean onlyMyGroups, Boolean regularEpisodesOnly, Int32 airingState)
>    at Shoko.Desktop.UserControls.MissingEpisodesControl.workerFiles_DoWork(Object sender, DoWorkEventArgs e) in C:\projects\jmmclient\Shoko.Desktop\UserControls\MissingEpisodesControl.xaml.cs:line 188
> ---> (Inner Exception #0) System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
>    at System.String.CreateStringFromEncoding(Byte* bytes, Int32 byteLength, Encoding encoding)
>    at System.Text.UTF8Encoding.GetString(Byte[] bytes, Int32 index, Int32 count)
>    at System.Net.Http.HttpContent.ReadBufferedContentAsString()
>    at System.Net.Http.HttpContent.<WaitAndReturnAsync>d__63`2.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Nancy.Rest.Client.Rest.SmallWebClient.<RestRequest>d__0.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Nancy.Rest.Client.ClientFactory.<>c__DisplayClass2_0.<<DoSyncClient>b__0>d.MoveNext()<---
> 
> [2017-09-19 15:50:09:055] Error|ExceptionWrapper.TryCatchWhen => Dispatcher.CatchException => App.Current_DispatcherUnhandledException System.NullReferenceException: Object reference not set to an instance of an object.
>    at Shoko.Desktop.UserControls.MissingEpisodesControl.workerFiles_RunWorkerCompleted(Object sender, RunWorkerCompletedEventArgs e) in C:\projects\jmmclient\Shoko.Desktop\UserControls\MissingEpisodesControl.xaml.cs:line 174
>    at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
>

**Comment by da3dsoul** [comment]
Buy more RAM! Sorry that's become an ongoing joke. I'll look at it

**Comment by bigretromike** [comment]
I can't its over 9000 already.

**Comment by da3dsoul** [comment]
Haha mine passed 9000 long ago, and it's not even in its final form

**Comment by ElementalCrisis** [comment]
Is this still an issue @bigretromike?
