### ISSUE TITLE
Invalid URI when deleting files on Windows Share

### ISSUE THREAD

**Issue by Darklyter** [ShokoAnime/ShokoDesktop#586]
Running current daily (2018-07-08), when trying to delete files that are located on a mapped windows share (V:\ANIME in this case) the process fails with an "Invalid URI: The format of the URI could not be determined" error.

Some builds have worked fine over the past few months, but more often than not I get this problem.  Here is the relevant log entry:

[2018-07-08 13:45:53:464] Error|CommandBinding.OnExecuted => UnrecognisedVideos.CommandBinding_DeleteFile => Utils.ShowErrorMessage System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at Shoko.Desktop.ViewModel.Server.VM_CloudAccount.<get_Bitmap>b__2_0() in C:\projects\jmmclient\Shoko.Desktop\ViewModel\Server\VM_CloudAccount.cs:line 30
   at System.Windows.Threading.Dispatcher.Invoke[TResult](Func`1 callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke[TResult](Func`1 callback)
   at Shoko.Desktop.ViewModel.Server.VM_CloudAccount.get_Bitmap() in C:\projects\jmmclient\Shoko.Desktop\ViewModel\Server\VM_CloudAccount.cs:line 26
   at Shoko.Desktop.Forms.AskDeleteFile.<>c.<.ctor>b__7_1(VM_CloudAccount a) in C:\projects\jmmclient\Shoko.Desktop\Forms\AskDeleteFile.xaml.cs:line 32
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Shoko.Desktop.Forms.AskDeleteFile..ctor(String title, String message, List`1 places) in C:\projects\jmmclient\Shoko.Desktop\Forms\AskDeleteFile.xaml.cs:line 31
   at Shoko.Desktop.UserControls.UnrecognisedVideos.CommandBinding_DeleteFile(Object sender, ExecutedRoutedEventArgs e) in C:\projects\jmmclient\Shoko.Desktop\UserControls\UnrecognisedVideos.xaml.cs:line 704

**Comment by ElementalCrisis** [comment]
Looks like it was fixed.
