### ISSUE TITLE
Fresh Install: Could not find a part of the path 'C:\ProgramData\ShokoDesktop\settings.json'.

### ISSUE THREAD

**Issue by 1ijack** [ShokoAnime/ShokoDesktop#588]
## PLEASE READ BEFORE POSTING YOUR ISSUE

_Please create GitHub issues only for bugs and feature requests. If you need help with using Shoko or have a question, join us on [Discord](https://discord.gg/vpeHDsg)._

_===== Guidelines ====_
- _Make sure you are using the latest **Stable** or **Daily** version of Shoko Server otherwise your issue will be closed._
- _Search this repository (top of the page) for the issue or feature you are reporting, make sure it has not been fixed or reported before._
- _If reporting an issue, then you must attach the relevant Shoko Server and Shoko Desktop_ **LOG FILE**. 
- _If requesting a new feature, please explain in detail the feature itself and the benefits of it being added._
- _If requesting cosmetic changes, please explain in detail why they should be made._ 
- _The template below_ **MUST BE USED** _when submitting an issue, no exceptions._

## VERSION INFORMATION
Server Version:  **3.9.2**    
Desktop Version: **3.9.2**    
_If you've compiled your own version, please use the last commit you compiled._

## LOG FILE
- CrashLog [2018-08-12.txt](https://cdn.discordapp.com/attachments/96235819366371328/478370831802826773/2018-08-12.txt
)    
````log
[2018-08-12 17:53:33:473] Error|App.Main => App..ctor => AppSettings.LoadSettings Error occured during LoadSettings: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\ProgramData\ShokoDesktop\settings.json'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at Shoko.Desktop.AppSettings.SaveSettings() in D:\Documents\GitHub\ShokoDesktop\Shoko.Desktop\AppSettings.cs:line 87
   at Shoko.Desktop.AppSettings.get_JMMServerInstance() in D:\Documents\GitHub\ShokoDesktop\Shoko.Desktop\AppSettings.cs:line 246
   at Shoko.Desktop.AppSettings.get_JMMServerPath() in D:\Documents\GitHub\ShokoDesktop\Shoko.Desktop\AppSettings.cs:line 58
   at Shoko.Desktop.AppSettings.get_JMMServerImagePath() in D:\Documents\GitHub\ShokoDesktop\Shoko.Desktop\AppSettings.cs:line 67
   at Shoko.Desktop.Utilities.Utils.GetBaseImagesPath() in D:\Documents\GitHub\ShokoDesktop\Shoko.Desktop\Utilities\Utils.cs:line 279
   at Shoko.Desktop.AppSettings.get_BaseImagesPath() in D:\Documents\GitHub\ShokoDesktop\Shoko.Desktop\AppSettings.cs:line 309
   at Shoko.Desktop.AppSettings.LoadSettings() in D:\Documents\GitHub\ShokoDesktop\Shoko.Desktop\AppSettings.cs:line 148
````

## DESCRIPTION
_Describe the problem you've encountered. What caused the issue, and what you expected to happen. Screenshot’s, Videos and any additional information is welcomed and will help us fix the problem._    

**Orig Attachment**: ShokoDesktop Log [2018-08-12.txt](https://cdn.discordapp.com/attachments/96235819366371328/478370831802826773/2018-08-12.txt) GitHub [anchor](./588#LOG+FILE)

**Orig Msg**: [478370832280846347](https://discordapp.com/channels/96234011612958720/96235819366371328/478370832280846347)    
Howdy, I just did a fresh install of Shoko Server+Desktop and I'm seeing a different behavior than I've experienced with prior versions.
 - [x] - _`Non-Issue`_ - Shoko Server does not have any options to specify MySQL DB.  Also, it did not prompt me to select/configure  the  DB at all.  My library is 5TB+, so I'd like to save on power/bandwidth unless necessary.  I could hack together the settings file to reflect my setup, but that'd lead us no-where for this issue.  
 - [ ] -  `missing settings.json during Install` -  Shoko Desktop, **created** the `C:\Program Files (x86)\Shoko\Shoko Desktop` **directory during the install,** but it **failed to create the settings file** `C:\ProgramData\ShokoDesktop\settings.json`  -- See attached [error log file](https://cdn.discordapp.com/attachments/96235819366371328/478370831802826773/2018-08-12.txt) GitHub [anchor](./588#LOG+FILE)    

**Orig Update** [478376564153647113](https://discordapp.com/channels/96234011612958720/96235819366371328/478376564153647113): 
 - [ ] - `missing settings.json during Install` -  Weird, I just tried relaunching Desktop (for the third time) and it created the settings.json file .  It's working now....    

## STEPS TO REPRODUCE
_Being as detailed as possible, please list all steps need to reproduce the issue, if we can't reproduce it then we can't fix it._
1.  Install fresh OS `Microsoft Windows [Version 10.0.17134.228]`    
2.  Download shokoDesktop and shokoServer 3.9.2    
3.  Run Installer    
4.   - [ ] -  `missing settings.json during Install` -

**Comment by da3dsoul** [comment]
He did. He just copied from discord

**Comment by 1ijack** [comment]
I dont know if I have the time, but, im planning on setting up a VM with the install/snapshots as to replicate the issue.  A huge reason I've thought about doing this is based on my validation/bug-repo background.  My **gross** (possibly delirious) assumptions: _in the order of probability_
1) issue can be an edge case pertaining to the server AND client launch+install+config states.  
2) not a shoko bug. _All/most factors are outside of Shoko's control/scope_
3) actual bug that is encountered with other edge case(s) and/or outside variables, but due to unknown factors cannot be reproduced easily (by devs).
4) bug is a sporadic, but apparent and seen by a good portion of users, but most users work resolve/work-around the issue with ease.

Maybe it's my pessimism from the my past, but these types of issues (without a stupid set of factors), can end up becoming a huge problem OR ignored/FAQ'd  for 15 years (and someone notices some quirky code, randomly throws a patch/pull-request that fixes the issue when no one cares anymore; ie, the source of the error was something totally stupid).

**Comment by bigretromike** [comment]
![1111](https://user-images.githubusercontent.com/6052025/79495862-88790800-8025-11ea-8ad7-3ec92204dc60.png)
From daily build
settings.json is missing;

**Comment by ElementalCrisis** [comment]
Issue is either fixed or user specific as it hasn't been reported since.
