### ISSUE TITLE
Error in Multiple Files tab

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/ShokoDesktop#600]
When expanding list of files linked to episode I sometimes get this error:

```

[2019-05-28 21:29:00:846] Error|AnimeFileSummaryControl.AnimeFileSummaryControl_DataContextChanged => AnimeFileSummaryControl.RefreshRecords => Utils.ShowErrorMessage System.AggregateException: One or more errors occurred. ---> Nancy.Rest.Client.Exceptions.RestClientException: Internal Server Error
   at Nancy.Rest.Client.Rest.SmallWebClient.<RestRequest>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nancy.Rest.Client.ClientFactory.<>c__DisplayClass2_0.<<DoSyncClient>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Nancy.Rest.Client.ClientFactory.DoSyncClient(Object dexp, MethodDefinition def, IWebProxy proxy, Object[] parameters)
   at Nancy.Rest.Client.ClientFactory.<>c__DisplayClass1_1`1.<Create>b__13(Object a)
   at CallSite.Target(Closure , CallSite , Object , Int32 )
   at ActLike_IShokoServer_06aa0cf716e04fe4b480a26efad114c2.GetGroupVideoQualitySummary(Int32 animeID)
   at Shoko.Desktop.UserControls.AnimeFileSummaryControl.RefreshRecords() in C:\projects\jmmclient\Shoko.Desktop\UserControls\AnimeFileSummaryControl.xaml.cs:line 233
---> (Inner Exception #0) Nancy.Rest.Client.Exceptions.RestClientException: Internal Server Error
   at Nancy.Rest.Client.Rest.SmallWebClient.<RestRequest>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nancy.Rest.Client.ClientFactory.<>c__DisplayClass2_0.<<DoSyncClient>b__0>d.MoveNext()<---
```

Download latest server/client

**Comment by Cazzar** [comment]
Nancy.Rest.Client.Exceptions.RestClientException: Internal Server Error


This indicates. A server error and issue

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into.
