### ISSUE TITLE
Shoko Desktop fails to start (application window not showing up)

### ISSUE THREAD

**Issue by SuperFlue** [ShokoAnime/ShokoDesktop#605]
## VERSION INFORMATION

Server Version: 4.0.0 (Docker)
Desktop Version: 4.0.0

## LOG FILE

```
[2020-09-27 13:19:51:407] Info|DefaultCtorXamlActivator.CreateInstance => DefaultCtorXamlActivator.CallCtorDelegate => MainWindow..ctor App startup - Loaded settings
[2020-09-27 13:19:52:988] Error|DefaultCtorXamlActivator.CreateInstance => DefaultCtorXamlActivator.CallCtorDelegate => MainWindow..ctor System.NullReferenceException: Object reference not set to an instance of an object.
   at Shoko.Desktop.MainWindow..ctor() in E:\Documents\GitHub\ShokoDesktop\Shoko.Desktop\MainWindow.xaml.cs:line 207
[2020-09-27 13:19:52:988] Error|ExceptionWrapper.TryCatchWhen => Dispatcher.CatchException => App.Current_DispatcherUnhandledException System.Windows.Markup.XamlParseException: Initialization of 'Shoko.Desktop.MainWindow' threw an exception. ---> System.InvalidOperationException: Cannot have nested BeginInit calls on the same instance.
   at System.Windows.FrameworkElement.BeginInit()
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.InitializationGuard(XamlType xamlType, Object obj, Boolean begin)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

## DESCRIPTION

The window for Shoko Desktop is not showing up, though task manager shows that the process is running.
Not sure what more to add except the log above (from %programdata%\ShokoDesktop\logs).

## STEPS TO REPRODUCE

Start ShokoDesktop and nothing seems to happen....

**Comment by da3dsoul** [comment]
That shouldn't be an issue in 4.0.1, but delete the section for File Quality... In settings-server.json (server settings) and delete the Desktop settings file

**Comment by SuperFlue** [comment]
That fixed it, thanks!

**Comment by da3dsoul** [comment]
Cool
