### ISSUE TITLE
ShokoDesktop Error on Startup

### ISSUE THREAD

**Issue by Gin-no-kami** [ShokoAnime/ShokoDesktop#610]
## VERSION INFORMATION

Server Version: 4.0.1.0

Desktop Version: 4.0.0

## LOG FILE

System.Windows.Markup.XamlParseException: The invocation of the constructor on type 'Shoko.Desktop.UserControls.MultipleFilesControl' that matches the specified binding constraints threw an exception. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: list
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.ObjectModel.ObservableCollection`1..ctor(List`1 list)
   at Shoko.Desktop.UserControls.MultipleFilesControl..ctor() in E:\Documents\GitHub\ShokoDesktop\Shoko.Desktop\UserControls\MultipleFilesControl.xaml.cs:line 245
   at System.Xaml.Schema.XamlTypeInvoker.DefaultCtorXamlActivator.CallCtorDelegate(XamlTypeInvoker type)
   at System.Xaml.Schema.XamlTypeInvoker.DefaultCtorXamlActivator.CreateInstance(XamlTypeInvoker type)
   at System.Xaml.Schema.XamlTypeInvoker.CreateInstance(Object[] arguments)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateInstance(XamlType xamlType, Object[] args)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at Shoko.Desktop.MainWindow..ctor() in E:\Documents\GitHub\ShokoDesktop\Shoko.Desktop\MainWindow.xaml.cs:line 144

## DESCRIPTION

ShokoDesktop does not start after updating from 3.9.7. Fully uninstalled/reinstalled and the same exact error persists. It is worth noting that I do not have a folder at "E:\Documents\*". 

## STEPS TO REPRODUCE

Run ShokoDesktop.exe. The program fails to launch and then the shoko_error.txt file is made with the same error message.

**Comment by ElementalCrisis** [comment]
Just did a fresh install of both and no issues. 

Start Shoko Server, wait until its loaded and then start Shoko Desktop. Wait about 10-15 seconds before trying anything as it can lock up and crash if you try to switch tabs after signing in.

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into.
